/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

object Versions {
    val Http4s = "1.0.0-M21"
    val Circe = "0.14.0-M5"
    val Cats = "2.3.0"
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.13.6")

    implementation("org.http4s:http4s-blaze-server_2.13:${Versions.Http4s}")
    implementation("org.http4s:http4s-ember-server_2.13:${Versions.Http4s}")
    implementation("org.http4s:http4s-ember-client_2.13:${Versions.Http4s}")
    implementation("org.http4s:http4s-circe_2.13:${Versions.Http4s}")
    implementation("org.http4s:http4s-dsl_2.13:${Versions.Http4s}")

    implementation("io.circe:circe-generic_2.13:${Versions.Circe}")

    implementation("org.typelevel:cats-core_2.13:${Versions.Cats}")
    implementation("org.typelevel:cats-effect_2.13:${Versions.Cats}")

    implementation("ch.qos.logback:logback-classic:1.2.10")
    implementation("com.typesafe.scala-logging:scala-logging_2.13:3.9.4")
    implementation("org.slf4j:slf4j-nop:1.6.4")

    implementation("com.typesafe.slick:slick_2.13:3.3.3")
    implementation("com.typesafe.slick:slick-hikaricp_2.13:3.3.3")

    implementation("com.github.pureconfig:pureconfig_2.13:0.17.1")

    implementation("org.postgresql:postgresql:42.1.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Use Scalatest for testing our library
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.scalatest:scalatest_2.13:3.2.9")
    testImplementation("org.scalatestplus:junit-4-13_2.13:3.2.2.0")

    // Need scala-xml at test runtime
    testRuntimeOnly("org.scala-lang.modules:scala-xml_2.13:1.2.0")
}

application {
    // Define the main class for the application.
    mainClass.set("com.workout.tracker.backend.Server")
}
